# Change these first
owner: pokt-foundation # Your GitHub organization or username, where this repository lives
repo: pokt-upptime # The name of this repository

sites:
  - name: Portal
    url: https://www.portal.pokt.network/
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: pokt-upptime 
  logoUrl: https://raw.githubusercontent.com/pokt-foundation/pokt-upptime/master/assets/Vector.png
  name: Pocket Network Status
  introTitle: "Service status"
  navbar:
    - title: Status
      href: /pokt-upptime/
    - title: Docs
      href: https://docs.pokt.network
    - title: Support
      href: https://support.pokt.network

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
